### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by pilsnerbeer** [ivpn/desktop-app-ui2#1]
# Bug report

## Describe your environment

* OS name and version:  2.12.3 IVPN deb package + latest beta appimage on ubuntu 20.04.1

## Describe the problem

places on map are showing all in the corner. see screenshot

### Steps to reproduce:

1. open app

### Observed Results:

![Screenshot from 2020-09-22 11-31-41](https://user-images.githubusercontent.com/36133540/93866096-877c8e80-fcc7-11ea-980f-c417a022130d.png)

* What happened? This could be a description, log output, etc.

**Comment by stenya** [comment]
@pilsnerbeer 
It is required to use the latest version of official IVPN software.
Please, update to the latest version of DEB package (v2.12.5). 
https://www.ivpn.net/apps-linux

**Comment by pilsnerbeer** [comment]
Problem fixed after update, thanks
