### ISSUE TITLE
Unable to see latencies for servers

### ISSUE THREAD

**Issue by NicholasJonesCode** [ivpn/desktop-app-ui2#16]
# Bug report

## Describe your environment

* Device: AMD-based desktop
* OS name and version: Windows 7 Pro 64 bit
* IVPN app version: 3.3.7

## Describe the problem

when i go to the server list, im not able to see any latencies for any of the servers, like i was able to with the old UI

### Steps to reproduce:

1. Click on the change server to pull up the server list
2. _____
3. _____

### Observed Results:

![Capture](https://user-images.githubusercontent.com/36060005/115816324-4c0d8400-a3be-11eb-916d-e4681e0bf36d.JPG)

### Expected Results:

* What did you expect to happen?

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment]
Hi @NicholasJonesCode 

There could be several reasons for that:

1. Option 'Autoconnect on launch' leads to IVPN is connecting immediately to the last selected server. So there was no enough time to ping servers. Servers pinging is disabled when the VPN is connected (because it has no sense).
2. The pinging process takes time. Usually, the ping status for the nearest servers can be seen in 3-6 seconds. But for pinging all servers needs a little bit more time. 
3. There is no internet connectivity

**Comment by NicholasJonesCode** [comment]
> 
> 
> Hi @NicholasJonesCode
> 
> There could be several reasons for that:
> 
>     1. Option 'Autoconnect on launch' leads to IVPN is connecting immediately to the last selected server. So there was no enough time to ping servers. Servers pinging is disabled when the VPN is connected (because it has no sense).
> 
>     2. The pinging process takes time. Usually, the ping status for the nearest servers can be seen in 3-6 seconds. But for pinging all servers needs a little bit more time.
> 
>     3. There is no internet connectivity

Okay, yeah, when i disconnect the VPN the Latencies do come up.. I guess i wasn't expecting that, the old UI did give me latencies even while connected, or at least i remember it like that.

I guess I would ask, could this be implemented? to have an option to ping even while connected? On the old UI I really appreciated seeing those while connected, because then I could switch servers easily to help me improve my connection.

**Comment by stenya** [comment]
@NicholasJonesCode I believe the old UI has the same behavior.

Regarding the possibility of ping servers in the connected state... There is already discussion of this topic here: https://github.com/ivpn/desktop-app-cli/issues/15
So here I have the same question:
What is the use case for it?
Pinging the servers in the connected state says nothing about real latency to your current location.
