### ISSUE TITLE
App not determining VPN status correctly

### ISSUE THREAD

**Issue by pilsnerbeer** [ivpn/desktop-app-ui2#2]
# Bug report

## Describe your environment

* OS name and version: 2.12.3 IVPN deb package + latest beta appimage on ubuntu 20.04.1

## Describe the problem

app seems to be "loading" vpn status forever after successfully connecting. 

### Steps to reproduce:

1. Disconnect from vpn if connected, see your ip
2. connect via UI
3. App will be loading indefinitely despite your connection already being active (can check through console)

### Observed Results:

Screenshot:

![Screenshot from 2020-09-22 11-36-02](https://user-images.githubusercontent.com/36133540/93866576-22756880-fcc8-11ea-81ad-ae15130206e3.png)

* What did you expect to happen?  
app should display a successful connection message but it never does

**Comment by stenya** [comment]
@pilsnerbeer 
It is required to use the latest version of official IVPN software.
Please, update to the latest version of DEB package (v2.12.5). 
https://www.ivpn.net/apps-linux
