### ISSUE TITLE
No icon

### ISSUE THREAD

**Issue by pilsnerbeer** [ivpn/desktop-app-ui2#3]
# Bug report

## Describe your environment

* OS name and version:  ubuntu 20.04 + GNOME  
* IVPN app version: both latest

### Steps to reproduce:

1. open ivpn appimage

### Observed Results:

The app shows no icon.

![Screenshot from 2020-09-23 21-06-02](https://user-images.githubusercontent.com/36133540/94058135-f13c8b80-fde0-11ea-9ac7-94e6f4e7189a.png)

### Expected Results:

Should have icon

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment]
Thank you. We already fixed that issue for Linux.
The updated sources will be available on Github soon.

**Comment by stenya** [comment]
fixed in v3.1.0
