### ISSUE TITLE
No autoconnect after suspending OS

### ISSUE THREAD

**Issue by d-b-96** [ivpn/desktop-app-ui2#4]
# Bug report

## Describe your environment

* Device: Laptop  
* OS name and version: Linux Mint 20.1  
* IVPN app version: v3.2.3

## Describe the problem
When logging in after suspending OS: app disconnects from server and does not autoconnect on launch.
(Autoconnect works fine when booting)

### Steps to reproduce:

1. Go to settings > General settings > Enable: "Launch at login", "Minimize to tray", "Autoconnect: On launch"
2. Suspend OS
3. Log in

### Observed Results:

* IVPN Icon in tray has green dot/shows connected
* After a few seconds green dot dissapears/shows disconnected
* Does not reconnect automatically

### Expected Results:

* IVPN establishes connection automaticcaly

**Comment by stenya** [comment]
@d-b-96 Can you, please update to v3.3.7 (just released)?
The issue should be fixed in this version.
