### ISSUE TITLE
Make the QR code on the account section bigger.

### ISSUE THREAD

**Issue by mystic-githuber** [ivpn/desktop-app-ui2#6]
Make the QR code on the account section bigger as I had trouble scanning.

**Comment by mystic-githuber** [comment]
@jurajhilje @stenya 

Thanks I am not a developer, github is still relatively new to me.

**Comment by stenya** [comment]
@mystic-githuber Version 3.3.7 is released. 
QR code now has a border (which increased its 'readability')
