### ISSUE TITLE
Minimize to system tray on when launched at login

### ISSUE THREAD

**Issue by TommyTran732** [ivpn/desktop-app-ui2#7]
# Feature request

## Description

An option to run IVPN-UI at startup, minimized to system tray on Linux would be nice. Right now it's always fully open which is kind of annoying.

I have not found any way to make it minize itself to the system tray or dock on GNOME yet.

**Comment by stenya** [comment]
@tommytran732 Please, try version 3.3.7 (just released).
It should work as you expect.

If you still have problems with the new version - feel free to reopen the ticket and provide us the information about the Linux distribution you use.

**Comment by mucke5** [comment]
@stenya I still don't see an option to enable this feature and it doesn't work in 3.3.7 either
I am using Ubuntu Budgie (latest LTS).
